language: c

before_install:
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update
  - sudo pip install cpp-coveralls

install: sudo apt-get install ninja-build

script: gcc -v && ./configure.py && ninja -v && ./base && ./waiters && ./channel && ./locks && ./bench

compiler:
  - gcc
  - clang

env:
  - CFLAGS="-O3"
  - CFLAGS="-O0"
  - CFLAGS="-O0 --coverage" LDFLAGS="--coverage"

after_success:
  - coveralls --exclude tests
